[project]
name = "dai"
version = "0.1.0"
description = "Distributed AI project of group 2. Combining Computer vision and machine learning to make a automated speed control"
readme = "README.md"
requires-python = "==3.8.20"
dependencies = [
    "carla>=0.9.15",
    "numpy>=1.24.4",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
